<a href="https://colab.research.google.com/github/majaszymajda/PNoD_rozpoznawanie_obraz/blob/main/Zadanie1_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Wczytanie danych


In [16]:
  import os
  import io
  import gzip
  import time
  import numpy as np
  import pandas as pd
  import sklearn
  import requests
  from sklearn.datasets import load_iris
  from sklearn.model_selection import train_test_split
  from sklearn.naive_bayes import GaussianNB
  from sklearn.ensemble import GradientBoostingClassifier
  from sklearn.metrics import confusion_matrix
  from sklearn.neighbors import KNeighborsClassifier


In [4]:
files = [
  "t10k-images-idx3-ubyte.gz",
  "t10k-labels-idx1-ubyte.gz",
  "train-images-idx3-ubyte.gz",
  "train-labels-idx1-ubyte.gz",
]

def download_and_save_locally(file):
    data = requests.get(f'https://github.com/zalandoresearch/fashion-mnist/raw/master/data/fashion/{file}')
    if data.status_code != 200:
      print(f"Blad pobierania pliku {file}")

    with open(file, "wb") as f:
      f.write(data.content)

    print(f"Pobrano plik {file}")
    # unzipped_content = gzip.open(io.BytesIO(data))
   # f'df{file}' = pd.read_csv(unzipped_content, delimiter='\t')
 
    # df{file}.head()

for f in files:
    download_and_save_locally(f)

Pobrano plik t10k-images-idx3-ubyte.gz
Pobrano plik t10k-labels-idx1-ubyte.gz
Pobrano plik train-images-idx3-ubyte.gz
Pobrano plik train-labels-idx1-ubyte.gz


In [5]:
def load_mnist(kind):
    """Load MNIST data from `path`"""
    with gzip.open(f'{kind}-labels-idx1-ubyte.gz', 'rb') as lbpath:
        # lbpath = pd.read_csv(lbpath)
        labels = np.frombuffer(lbpath.read(), dtype=np.uint8,
                              offset=8)

    with gzip.open(f'{kind}-images-idx3-ubyte.gz', 'rb') as imgpath:
        images = np.frombuffer(imgpath.read(), dtype=np.uint8,
                              offset=16).reshape(len(labels), 784)

    return images, labels

In [ ]:
def load_mnist_vol2():
  data_train = pd.reas_csv()

In [7]:
X_train, y_train = load_mnist(kind='train')
X_test, y_test = load_mnist(kind='t10k')

print(X_train.shape)
print(X_test.shape)
print(y_train)

# X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.20)

(60000, 784)
(10000, 784)
[9 0 0 ... 3 0 5]


In [ ]:
def sort_train_labels_knn(Dist, y):
    
    return y[Dist.argsort(kind='mergesort')]

In [ ]:
def hamming_distance(X, X_train):
    Xrev = 1-X
    X = X.astype(int)
    X_trainrev = 1 - X_train
    X_trainint = X_train.astype(int)
    # print(Xrev @ X_trainint.transpose() + X @ X_trainrev.transpose())
    return Xrev @ X_trainint.transpose() + X @ X_trainrev.transpose()

In [ ]:

def model_selection_knn(Xval, Xtrain, yval, ytrain, k_values):
    
    errors = []
    srted_et = sort_train_labels_knn(hamming_distance(Xval, Xtrain), ytrain)
    best_k = 0
    min_er = 1
    for k in k_values:
        er = classification_error(p_y_x_knn(srted_et, k), yval)
        errors.append(er)
        if er < min_er:
            best_k = k
            min_er = er
    return min_er, best_k, errors

# Ekstrakcja cehc 
zamiast filtrów używam randoma XD



In [8]:
np.random.seed(0)
val_1_id = np.random.choice(60000, 10000, replace=False)
val_2_id = np.random.choice(list(set(range(60000)) - set(val_1_id)), 10000, replace=False)
train_id = list(set(range(60000))- set(val_2_id)- set(val_1_id))

X_train_1 = X_train[train_id]
y_train_1 = y_train[train_id]

x_valid_1 = X_train[val_2_id]
y_valid_1 = y_train[val_2_id]

x_valid_2 = X_train[val_1_id]
y_valid_2 = y_train[val_1_id]

# fitting KNN for k = 1 - ilośc sądiadów 

KNN_model_k_1 = KNeighborsClassifier(n_neighbors=1).fit(X_train_1, y_train_1)



# Training Accuracy

In [9]:
confusion_matrix(KNN_model_k_1.predict(X_train_1), y_train_1)

array([[4042,    0,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0, 4051,    0,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0, 3916,    0,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0, 4016,    0,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0, 3971,    0,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0, 3976,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0, 4013,    0,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0, 4002,    0,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0, 4055,    0],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0, 3958]])

In [11]:
KNN_model_k_1_accuracy = (KNN_model_k_1.predict(X_train_1) == y_train_1).mean()
print("TRAINING ACCURACY:", KNN_model_k_1_accuracy)

TRAINING ACCURACY: 1.0


In [12]:
confusion_matrix(KNN_model_k_1.predict(x_valid_1), y_valid_1)

array([[802,   2,  16,  35,   8,   2, 172,   0,   7,   0],
       [  3, 922,   0,   4,   1,   0,   1,   0,   0,   0],
       [ 26,   2, 833,   8, 117,   0, 128,   0,  10,   1],
       [ 21,  16,   9, 834,  33,   0,  23,   0,   2,   0],
       [  4,   1, 107,  31, 745,   0,  67,   0,   6,   0],
       [  1,   0,   0,   0,   0, 866,   0,   5,   0,   2],
       [128,   5,  98,  45, 105,   3, 625,   0,  14,   0],
       [  0,   0,   0,   0,   0,  79,   0, 971,   1,  29],
       [  3,   0,   1,   2,   2,   4,   4,   0, 908,   1],
       [  0,   0,   1,   0,   0,  48,   0,  63,   3, 984]])

In [14]:
KNN_model_k_1_accuracy = (KNN_model_k_1.predict(x_valid_1) == y_valid_1).mean()
print("TRAINING ACCURACY:", KNN_model_k_1_accuracy)

TRAINING ACCURACY: 0.849


Gdy przyjmujemy jako ilość sąsiadów k = 5

In [ ]:
start = time.clock()
KNN_model_k_5 = KNeighborsClassifier(n_neighbors=5).fit(X_train_1, y_train_1)
confusion_matrix(KNN_model_k_5.predict(x_valid_1), y_valid_1)
KNN_model_k_5_accuracy = (KNN_model_k_5.predict(X_train_1) == y_train_1).mean()
print("TRAINING ACCURACY:", KNN_model_k_5_accuracy)
end = time.clock()
total = end - start
print(f'time:{total}' )

Fitting Gradient Boosting - metoda klasyfikacji wykorzystująca 

In [ ]:
GBST_model = GradientBoostingClassifier(n_estimators=1000, learning_rate=0.5).fit(X_train, y_train)

KeyboardInterrupt: ignored

In [ ]:
confusion_matrix(GBST_model.predict(X_train),y_train)

In [ ]:
KNN_model_type_1 = sklearn.neighbors.KNeighborsClassifier(n_neighbors=1).fit(X_train, y_train)
confusion_matrix(KNN_model_type_1.predict(X_train),y_train)

KeyboardInterrupt: ignored

In [ ]:

def model_selection_knn(Xval, Xtrain, yval, ytrain, k_values):
    """
    :param Xval: zbior danych walidacyjnych N1xD
    :param Xtrain: zbior danych treningowych N2xD
    :param yval: etykiety klas dla danych walidacyjnych 1xN1
    :param ytrain: etykiety klas dla danych treningowych 1xN2
    :param k_values: wartosci parametru k, ktore maja zostac sprawdzone
    :return: funkcja wykonuje selekcje modelu knn i zwraca krotke (best_error,best_k,errors), gdzie best_error to najnizszy
    osiagniety blad, best_k - k dla ktorego blad byl najnizszy, errors - lista wartosci bledow dla kolejnych k z k_values
    """
    errors = []
    srted_et = sort_train_labels_knn(hamming_distance(Xval, Xtrain), ytrain)
    best_k = 0
    min_er = 1
    for k in k_values:
        er = classification_error(p_y_x_knn(srted_et, k), yval)
        errors.append(er)
        if er < min_er:
            best_k = k
            min_er = er
    return min_er, best_k, errors

In [ ]:
KNN_model_type_1_acc = (KNN_model_type_1.predict(X_train) == y_train).mean()
print("TRAINING ACCURACY=", KNN_model_type_1_acc)

In [ ]:
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)

model = LogisticRegression()
model.fit(X_train, y_train)

y_predicted = model.predict(X_test)

accuracy_score(y_test, y_predicted)

confusion_matrix(y_test, y_predicted)

bal = LogisticRegression(random_state=0, class_weight='balanced')
bal.fit(X_train, y_train)
y_predicted = bal.predict(X_test)
accuracy_score(y_test, y_predicted)

confusion_matrix(y_test, y_predicted)



array([[ 8,  0,  0],
       [ 0,  7,  0],
       [ 0,  0, 15]])

In [ ]:
X, y = load_iris(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=0)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)
print("Number of mislabeled points out of a total %d points : %d"  % (X_test.shape[0], (y_test != y_pred).sum()))
print(y_pred)

Number of mislabeled points out of a total 75 points : 4
[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 1 1 1 2 0 2 0 0 1 2 2 1 2 1 2 1 1 2 1 1 2 1 2 1 0 2 1 1 1 1 2 0 0 2 1 0 0
 1]


## Zadanie 3
Należy sprawdzić jakość jednego z modeli z poprzednich zadań (Naive Bayes, K-NN, Regresja  Logistyczna) na zbiorzeFashionMnist. W tym celu należy wyuczyć model na danych treningowych i ocenić jego jakość na danych testowych w oparciu o poprawność klasyfikacji.W dalszej kolejności należy skonfrontować swój wynik z wynikiem otrzymanym w ramach http://fashion-mnist.s3-website.eu-central-1.amazonaws.com/dla  odpowiadającejmetody i przeanalizować ewentualne różnice.